#!/usr/bin/env python3
"""Generate supabase/seed/raid_events_seed.sql from raid_boss_event.json.
Run from repo root:  python3 supabase/tools/import_raids.py  (then run the seed
in Supabase after 0003)."""
import json, os

SCALARS = ['raid_id','name','region','min_level','recommended_party_size',
           'max_player','spawn_time_ends','time_limit','boss_monster_id',
           'raid_type','max_entry']
JSONB = ['entry_requirements','spawn_monster_id','phases','clear_rewards']
COLS = SCALARS + JSONB + ['sort_order']

def s(v): return 'NULL' if v is None else "'" + str(v).replace("'", "''") + "'"
def i(v): return 'NULL' if v is None else str(int(v))
def jb(o): return "'" + json.dumps(o, ensure_ascii=False).replace("'", "''") + "'::jsonb"

def main():
    root = os.getcwd()
    raids = json.load(open(os.path.join(root, 'raid_boss_event.json')))['raids']
    rows = []
    for order, r in enumerate(raids):
        vals = []
        for c in SCALARS:
            v = r.get(c)
            vals.append(i(v) if isinstance(v, int) and not isinstance(v, bool) else s(v))
        for c in JSONB:
            vals.append(jb(r.get(c) if r.get(c) is not None else ([] if c != 'clear_rewards' else {})))
        vals.append(str(order))
        rows.append(vals)
    out = os.path.join(root, 'supabase', 'seed', 'raid_events_seed.sql')
    with open(out, 'w') as f:
        f.write('-- AUTO-GENERATED by supabase/tools/import_raids.py — do not edit.\n')
        f.write(f'-- {len(rows)} raid events.\nbegin;\n')
        upd = ', '.join(f'{c}=excluded.{c}' for c in COLS if c != 'raid_id')
        for r in rows:
            f.write(f'insert into public.raid_events ({", ".join(COLS)})\n'
                    f'values ({", ".join(r)})\non conflict (raid_id) do update set {upd};\n')
        f.write('commit;\n')
    print(f'WROTE {out}  ({len(rows)} raid events)')

if __name__ == '__main__':
    main()
