#!/usr/bin/env python3
"""Generate supabase/seed/shops_seed.sql from shop_inventory.json.

Run from repo root:  python3 supabase/tools/import_shops.py
Then run supabase/seed/shops_seed.sql in the Supabase SQL editor (after 0002).
"""
import json, os

def s(v): return 'NULL' if v is None else "'" + str(v).replace("'", "''") + "'"
def i(v): return '0' if v is None else str(int(v))
def num(v): return '1.0' if v is None else repr(float(v))

def main():
    root = os.getcwd()
    data = json.load(open(os.path.join(root, 'shop_inventory.json')))
    shops = data['shops']
    shop_rows, item_rows = [], []
    seen_item = set()
    for si, shop in enumerate(shops):
        shop_rows.append((s(shop['id']), s(shop.get('name', shop['id'])),
                          s(shop.get('faction')), s(shop.get('buy_currency')),
                          s(shop.get('description')), str(si)))
        order = 0
        for cat in (shop.get('categories') or []):
            cname = cat.get('category', '')
            for it in (cat.get('items') or []):
                key = (shop['id'], cname, it['item_id'])
                if key in seen_item:
                    print(f'  WARN duplicate {key} skipped')
                    continue
                seen_item.add(key)
                item_rows.append((s(shop['id']), s(cname), s(it['item_id']),
                                  i(it.get('stock')), i(it.get('refresh_time')),
                                  num(it.get('price_modifier')), str(order)))
                order += 1

    out = os.path.join(root, 'supabase', 'seed', 'shops_seed.sql')
    with open(out, 'w') as f:
        f.write('-- AUTO-GENERATED by supabase/tools/import_shops.py — do not edit.\n')
        f.write(f'-- {len(shop_rows)} shops, {len(item_rows)} shop items.\n')
        f.write('begin;\n')
        for r in shop_rows:
            f.write('insert into public.shops (id, name, faction, buy_currency, description, sort_order)\n'
                    f'values ({", ".join(r)})\n'
                    'on conflict (id) do update set name=excluded.name, faction=excluded.faction, '
                    'buy_currency=excluded.buy_currency, description=excluded.description, '
                    'sort_order=excluded.sort_order;\n')
        for r in item_rows:
            f.write('insert into public.shop_items (shop_id, category, item_id, stock, refresh_time, price_modifier, sort_order)\n'
                    f'values ({", ".join(r)})\n'
                    'on conflict (shop_id, category, item_id) do update set stock=excluded.stock, '
                    'refresh_time=excluded.refresh_time, price_modifier=excluded.price_modifier, '
                    'sort_order=excluded.sort_order;\n')
        f.write('commit;\n')
    print(f'WROTE {out}  ({len(shop_rows)} shops, {len(item_rows)} items)')

if __name__ == '__main__':
    main()
