#!/usr/bin/env python3
"""Generate chunked skill seed SQL from skill_list.json (top-level list).
Run:  python3 supabase/tools/import_skills.py"""
import json, os

TEXT_REQ  = ['id','name','type','source_type','damage_formula','effect','skill_description','skill_shape']
TEXT_OPT  = ['target_attack','target_effect']
NUM_REQ   = ['range','aoe_radius','projectile_speed','cooldown_seconds']  # numeric
NUM_OPT   = ['arc_angle_degrees']
INT_REQ   = ['mp_cost']
JSONB_REQ = ['stat_modifiers','periodic_effects','control_effects']
JSONB_OPT = ['special_effects','usage_requirements']
# column order for INSERT (quote reserved "range")
COLS = ['id','name','type','source_type','mp_cost','damage_formula','effect',
        'skill_description','skill_shape','"range"','aoe_radius','projectile_speed',
        'cooldown_seconds','arc_angle_degrees','target_attack','target_effect',
        'stat_modifiers','periodic_effects','control_effects','special_effects',
        'usage_requirements','sort_order']

def s(v): return 'NULL' if v is None else "'" + str(v).replace("'", "''") + "'"
def n(v): return 'NULL' if v is None else repr(float(v))
def iv(v): return '0' if v is None else str(int(v))
def jb(o): return 'NULL' if o is None else "'" + json.dumps(o, ensure_ascii=False).replace("'", "''") + "'::jsonb"

def rowvals(sk, order):
    return [
        s(sk.get('id')), s(sk.get('name')), s(sk.get('type')), s(sk.get('source_type')),
        iv(sk.get('mp_cost')), s(sk.get('damage_formula')), s(sk.get('effect')),
        s(sk.get('skill_description')), s(sk.get('skill_shape')),
        n(sk.get('range')), n(sk.get('aoe_radius')), n(sk.get('projectile_speed')),
        n(sk.get('cooldown_seconds')), n(sk.get('arc_angle_degrees')),
        s(sk.get('target_attack')), s(sk.get('target_effect')),
        jb(sk.get('stat_modifiers') or []), jb(sk.get('periodic_effects') or []),
        jb(sk.get('control_effects') or []),
        jb(sk['special_effects']) if 'special_effects' in sk else 'NULL',
        jb(sk['usage_requirements']) if 'usage_requirements' in sk else 'NULL',
        str(order),
    ]

def main():
    root = os.getcwd()
    skills = json.load(open(os.path.join(root, 'skill_list.json')))
    rows = [rowvals(sk, i) for i, sk in enumerate(skills)]
    collist = ', '.join(COLS)
    upd = ', '.join(f'{c}=excluded.{c}' for c in COLS if c != 'id')
    def write(path, rws, note):
        with open(path, 'w') as f:
            f.write(f'-- AUTO-GENERATED by import_skills.py — {note}\nbegin;\n')
            for r in rws:
                f.write(f'insert into public.skills ({collist})\nvalues ({", ".join(r)})\n'
                        f'on conflict (id) do update set {upd};\n')
            f.write('commit;\n')
    seed = os.path.join(root, 'supabase', 'seed')
    write(os.path.join(seed, 'skills_seed.sql'), rows, f'{len(rows)} skills.')
    CHUNK = 150
    for old in [p for p in os.listdir(seed) if p.startswith('skills_seed_part')]:
        os.remove(os.path.join(seed, old))
    parts = [rows[x:x+CHUNK] for x in range(0, len(rows), CHUNK)]
    for k, ch in enumerate(parts, 1):
        write(os.path.join(seed, f'skills_seed_part{k:02d}.sql'), ch, f'skills part {k}/{len(parts)}.')
    print(f'WROTE skills_seed.sql ({len(rows)}) + {len(parts)} chunks (skills_seed_part01..{len(parts):02d}.sql)')

if __name__ == '__main__':
    main()
