#!/usr/bin/env python3
"""Generate ally seed SQL from ally_list.json.  Run: python3 supabase/tools/import_allies.py"""
import json, os

COLS = ['ally_id','code','name','rarity','role','brief_background_story',
        'place_of_origin','faction_affinity','base_stats','passive_skill_id',
        'active_skill_id','recruit_cost','level_cap','pvp_scale','conclave_points','sort_order']

def s(v): return 'NULL' if v is None else "'" + str(v).replace("'", "''") + "'"
def iv(v): return 'NULL' if v is None else str(int(v))
def nv(v): return 'NULL' if v is None else repr(float(v))
def jb(o): return "'" + json.dumps(o or {}, ensure_ascii=False).replace("'", "''") + "'::jsonb"

def main():
    root = os.getcwd()
    allies = json.load(open(os.path.join(root, 'ally_list.json')))['allies']
    rows = []
    for order, a in enumerate(allies):
        rows.append([
            s(a.get('ally_id')), s(a.get('code')), s(a.get('name')), s(a.get('rarity')),
            s(a.get('role')), s(a.get('brief_background_story')), s(a.get('place_of_origin')),
            s(a.get('faction_affinity')), jb(a.get('base_stats')),
            s((a.get('passive_skill') or {}).get('skill_id')),
            s((a.get('active_skill') or {}).get('skill_id')),
            iv(a.get('recruit_cost')), iv(a.get('level_cap')),
            nv(a.get('pvp_scale')), iv(a.get('conclave_points')), str(order),
        ])
    collist = ', '.join(COLS)
    upd = ', '.join(f'{c}=excluded.{c}' for c in COLS if c != 'ally_id')
    out = os.path.join(root, 'supabase', 'seed', 'allies_seed.sql')
    with open(out, 'w') as f:
        f.write(f'-- AUTO-GENERATED by import_allies.py — {len(rows)} allies.\nbegin;\n')
        for r in rows:
            f.write(f'insert into public.allies ({collist})\nvalues ({", ".join(r)})\n'
                    f'on conflict (ally_id) do update set {upd};\n')
        f.write('commit;\n')
    print(f'WROTE {out} ({len(rows)} allies, {os.path.getsize(out)//1024} KB)')

if __name__ == '__main__':
    main()
