#!/usr/bin/env python3
"""Generate npc seed SQL from npc_list.json.  Run: python3 supabase/tools/import_npcs.py"""
import json, os

TEXT = ['npc_id','name','title','role','faction','location','region_id','description',
        'personality','greeting','shop_inventory','dialogue_tree','buy_currency',
        'rest_currency','sell_note','quest_category','reward_currency']
JSONB = ['available_services','actions']
COLS = TEXT + JSONB + ['sort_order']

def s(v): return 'NULL' if v is None else "'" + str(v).replace("'", "''") + "'"
def jb(o): return "'" + json.dumps(o or [], ensure_ascii=False).replace("'", "''") + "'::jsonb"

def main():
    root = os.getcwd()
    npcs = json.load(open(os.path.join(root, 'npc_list.json')))
    if isinstance(npcs, dict):
        npcs = npcs.get('npcs', [])
    rows = []
    for order, n in enumerate(npcs):
        if 'npc_id' not in n:
            continue
        v = [s(n.get(k)) for k in TEXT] + [jb(n.get(c)) for c in JSONB] + [str(order)]
        rows.append(v)
    collist = ', '.join(COLS)
    upd = ', '.join(f'{c}=excluded.{c}' for c in COLS if c != 'npc_id')
    def write(path, rws, note):
        with open(path, 'w') as f:
            f.write(f'-- AUTO-GENERATED by import_npcs.py — {note}\nbegin;\n')
            for r in rws:
                f.write(f'insert into public.npcs ({collist})\nvalues ({", ".join(r)})\n'
                        f'on conflict (npc_id) do update set {upd};\n')
            f.write('commit;\n')
    seed = os.path.join(root, 'supabase', 'seed')
    write(os.path.join(seed, 'npcs_seed.sql'), rows, f'{len(rows)} npcs.')
    CHUNK = 80
    for old in [p for p in os.listdir(seed) if p.startswith('npcs_seed_part')]:
        os.remove(os.path.join(seed, old))
    size = os.path.getsize(os.path.join(seed, 'npcs_seed.sql'))
    parts = [rows[x:x+CHUNK] for x in range(0, len(rows), CHUNK)]
    if size > 800_000:  # chunk only if the single file risks the editor cap
        for k, ch in enumerate(parts, 1):
            write(os.path.join(seed, f'npcs_seed_part{k:02d}.sql'), ch, f'npcs part {k}/{len(parts)}.')
        print(f'WROTE npcs_seed.sql ({len(rows)}) + {len(parts)} chunks ({size//1024} KB).')
    else:
        print(f'WROTE npcs_seed.sql ({len(rows)} npcs, {size//1024} KB — fits one paste).')

if __name__ == '__main__':
    main()
