#!/usr/bin/env python3
"""Generate chunked dialog seed SQL from dialog_tree_master.json + dialog_quests.json.
Run:  python3 supabase/tools/import_dialogs.py"""
import json, os

COLS = ['dialog_id','quest_id','npc_id','start_node','nodes','source_file','sort_order']

def s(v): return 'NULL' if v is None else "'" + str(v).replace("'", "''") + "'"
def jb(o): return "'" + json.dumps(o or [], ensure_ascii=False).replace("'", "''") + "'::jsonb"

def dialogues(fn):
    d = json.load(open(fn))
    if isinstance(d, dict):
        return d.get('dialogues', [])
    out = []
    for it in d:            # list of {dialogues:[...]} wrappers
        if isinstance(it, dict):
            out += it.get('dialogues', [])
    return out

def main():
    root = os.getcwd()
    rows = []
    order = 0
    for fn in ['dialog_tree_master.json', 'dialog_quests.json']:
        for e in dialogues(os.path.join(root, fn)):
            if not isinstance(e, dict) or 'dialog_id' not in e:
                continue
            rows.append([s(e.get('dialog_id')), s(e.get('quest_id')), s(e.get('npc_id')),
                         s(e.get('start_node')), jb(e.get('nodes')), s(fn), str(order)])
            order += 1
    collist = ', '.join(COLS)
    upd = ', '.join(f'{c}=excluded.{c}' for c in COLS if c != 'dialog_id')
    def write(path, rws, note):
        with open(path, 'w') as f:
            f.write(f'-- AUTO-GENERATED by import_dialogs.py — {note}\nbegin;\n')
            for r in rws:
                f.write(f'insert into public.dialogs ({collist})\nvalues ({", ".join(r)})\n'
                        f'on conflict (dialog_id) do update set {upd};\n')
            f.write('commit;\n')
    seed = os.path.join(root, 'supabase', 'seed')
    write(os.path.join(seed, 'dialogs_seed.sql'), rows, f'{len(rows)} dialogs.')
    CHUNK = 120
    for old in [p for p in os.listdir(seed) if p.startswith('dialogs_seed_part')]:
        os.remove(os.path.join(seed, old))
    parts = [rows[x:x+CHUNK] for x in range(0, len(rows), CHUNK)]
    for k, ch in enumerate(parts, 1):
        write(os.path.join(seed, f'dialogs_seed_part{k:02d}.sql'), ch, f'dialogs part {k}/{len(parts)}.')
    print(f'WROTE dialogs_seed.sql ({len(rows)}) + {len(parts)} chunks (dialogs_seed_part01..{len(parts):02d}.sql)')

if __name__ == '__main__':
    main()
