#!/usr/bin/env python3
"""Generate chunked item seed SQL from item_list.json (dedup last-wins).

Run:  python3 supabase/tools/import_items.py
Produces seed/items_seed.sql (full, for psql) + items_seed_partNN.sql chunks
(for the SQL editor size cap). Prints the duplicate-id conflicts to review.
"""
import json, os
from collections import defaultdict

SCALARS = ['id','name','type','rarity','level_requirement','buy_price',
           'sell_price','sell_value','max_stack','icon_image','description']
JSONB = ['equipment_slots','stats_bonus','special_effects']
COLS = SCALARS + JSONB + ['sort_order']

def s(v): return 'NULL' if v is None else "'" + str(v).replace("'", "''") + "'"
def i(v): return 'NULL' if v is None else str(int(v))
def jb(o): return "'" + json.dumps(o, ensure_ascii=False).replace("'", "''") + "'::jsonb"

def main():
    root = os.getcwd()
    raw = json.load(open(os.path.join(root, 'item_list.json')))['items']
    # last-wins dedup, remember the (last) position for stable ordering
    by_id, pos = {}, {}
    groups = defaultdict(list)
    for idx, it in enumerate(raw):
        by_id[it['id']] = it        # last wins (matches client _itemById map)
        pos[it['id']] = idx
        groups[it['id']].append(it)
    # conflict report
    conflicts = []
    for k, v in groups.items():
        if len(v) > 1 and len({json.dumps(x, sort_keys=True) for x in v}) > 1:
            conflicts.append((k, len(v)))
    ordered = sorted(by_id.values(), key=lambda it: pos[it['id']])

    def row(it):
        vals = []
        for c in SCALARS:
            v = it.get(c)
            vals.append(i(v) if isinstance(v, int) and not isinstance(v, bool) else s(v))
        for c in JSONB:
            default = {} if c == 'stats_bonus' else []
            vals.append(jb(it.get(c) if it.get(c) is not None else default))
        vals.append(str(pos[it['id']]))
        return vals

    collist = ', '.join(COLS)
    upd = ', '.join(f'{c}=excluded.{c}' for c in COLS if c != 'id')
    def write(path, rows, note):
        with open(path, 'w') as f:
            f.write(f'-- AUTO-GENERATED by import_items.py — {note}\nbegin;\n')
            for r in rows:
                f.write(f'insert into public.items ({collist})\nvalues ({", ".join(r)})\n'
                        f'on conflict (id) do update set {upd};\n')
            f.write('commit;\n')

    seed_dir = os.path.join(root, 'supabase', 'seed')
    rows = [row(it) for it in ordered]
    write(os.path.join(seed_dir, 'items_seed.sql'), rows, f'{len(rows)} unique items (last-wins dedup).')
    CHUNK = 150
    for old in [p for p in os.listdir(seed_dir) if p.startswith('items_seed_part')]:
        os.remove(os.path.join(seed_dir, old))
    parts = [rows[x:x + CHUNK] for x in range(0, len(rows), CHUNK)]
    for n, ch in enumerate(parts, 1):
        write(os.path.join(seed_dir, f'items_seed_part{n:02d}.sql'), ch, f'items part {n}/{len(parts)}.')

    print(f'{len(raw)} raw items -> {len(rows)} unique (dropped {len(raw)-len(rows)} dup rows).')
    print(f'WROTE items_seed.sql + {len(parts)} chunks (items_seed_part01..{len(parts):02d}.sql).')
    print(f'\n{len(conflicts)} CONFLICTING duplicate ids (differing data — review & fix prices in DB):')
    for k, n in sorted(conflicts): print(f'   {k} ({n}x)')

if __name__ == '__main__':
    main()
