#!/usr/bin/env python3
"""Generate supabase/seed/quests_seed.sql from the 8 quest_*.json files.

Run from the repo root:  python3 supabase/tools/import_quests.py
Then paste supabase/seed/quests_seed.sql into the Supabase SQL editor (after
running supabase/migrations/0001_quests.sql once).

This is the one-time lift of the quest catalogue into the `public.quests`
table. After this, edit quests in Supabase and use export_quests.py to publish
the JSON back to the CDN — the Flutter client stays unchanged.
"""
import json, os

# source file -> the output filename export must regenerate (round-trip)
FILES = [
    'quest_list.json', 'quest_arcanum.json', 'quest_concordium.json',
    'quest_iron.json', 'quest_legion.json', 'quest_meridian.json',
    'quest_omnicorp.json', 'quest_shard.json', 'quest_neutral.json',
    'quest_events.json',
]
COLS = ['id','title','type','rank','faction','region','description',
        'quest_giver','requirements','objectives','rewards','repeatable',
        'daily','quest_chain_next','popup','popup_trigger','popup_level',
        'popup_prerequisite','source_file','sort_order']

def s(v):
    return 'NULL' if v is None else "'" + str(v).replace("'", "''") + "'"
def jb(obj):
    return "'" + json.dumps(obj or {}, ensure_ascii=False).replace("'", "''") + "'::jsonb"
def b(v):
    return 'true' if v else 'false'
def i(v):
    return 'NULL' if v is None else str(int(v))

def main():
    root = os.getcwd()
    rows = []
    seen = set()
    for fname in FILES:
        path = os.path.join(root, fname)
        if not os.path.exists(path):
            continue
        data = json.load(open(path))
        quests = data.get('quests', data) if isinstance(data, dict) else data
        for order, q in enumerate(quests):
            if not isinstance(q, dict) or 'id' not in q:
                continue
            qid = q['id']
            if qid in seen:
                print(f'  WARN duplicate id skipped: {qid} ({fname})')
                continue
            seen.add(qid)
            rows.append((
                s(qid), s(q.get('title', qid)), s(q.get('type')), s(q.get('rank')),
                s(q.get('faction', '')), s(q.get('region')), s(q.get('description')),
                jb(q.get('quest_giver')), jb(q.get('requirements')),
                jb(q.get('objectives') or []), jb(q.get('rewards')),
                b(q.get('repeatable')), b(q.get('daily')),
                s(q.get('quest_chain_next')), b(q.get('popup')),
                s(q.get('popup_trigger')), i(q.get('popup_level')),
                s(q.get('popup_prerequisite')), s(fname), str(order),
            ))

    collist = ', '.join(COLS)
    upd = ', '.join(f'{c} = excluded.{c}' for c in COLS if c != 'id')

    def write_rows(path, rws, note):
        with open(path, 'w') as f:
            f.write('-- AUTO-GENERATED by supabase/tools/import_quests.py — do not edit by hand.\n')
            f.write(f'-- {note}\nbegin;\n')
            for r in rws:
                f.write(f'insert into public.quests ({collist})\nvalues ({", ".join(r)})\n'
                        f'on conflict (id) do update set {upd};\n')
            f.write('commit;\n')

    seed_dir = os.path.join(root, 'supabase', 'seed')
    # full file (for psql / CLI — no size limit)
    write_rows(os.path.join(seed_dir, 'quests_seed.sql'), rows,
               f'{len(rows)} quests from {len([x for x in FILES if os.path.exists(x)])} files.')
    # chunked files (~150 rows each) — each fits the Supabase SQL Editor size cap.
    # Run them in order: quests_seed_part01.sql, part02, ...
    CHUNK = 150
    parts = [rows[i:i + CHUNK] for i in range(0, len(rows), CHUNK)]
    for old in [p for p in os.listdir(seed_dir) if p.startswith('quests_seed_part')]:
        os.remove(os.path.join(seed_dir, old))
    for idx, chunk in enumerate(parts, 1):
        write_rows(os.path.join(seed_dir, f'quests_seed_part{idx:02d}.sql'), chunk,
                   f'quests part {idx}/{len(parts)} ({len(chunk)} rows).')
    print(f'WROTE quests_seed.sql ({len(rows)} quests) + {len(parts)} chunk files '
          f'quests_seed_part01..{len(parts):02d}.sql (~{CHUNK} rows each)')

if __name__ == '__main__':
    main()
