#!/usr/bin/env python3
"""Generate monster seed SQL from monster_master.json.
Run:  python3 supabase/tools/import_monsters.py  (chunks if large)"""
import json, os

INT   = ['monster_id','level','exp_reward','currency_reward','crd_reward',
         'guild_point','reputation_point','hunting_point']
NUM   = ['critical_rate','critical_damage']
TEXT  = ['code','name','rank','race_code','spawn_monster_id']
JSONB = ['element','spawn_location','base_stats','scaling','resistances',
         'weaknesses','status_immunity','ai_pattern','skill_set','drop_item','special_reward']
COLS  = ['monster_id','code','name','rank','level','race_code','spawn_monster_id',
         'critical_rate','critical_damage','exp_reward','currency_reward','crd_reward',
         'guild_point','reputation_point','hunting_point'] + JSONB + ['sort_order']

def s(v): return 'NULL' if v is None else "'" + str(v).replace("'", "''") + "'"
def iv(v): return 'NULL' if v is None else str(int(v))
def nv(v): return 'NULL' if v is None else repr(float(v))
def jb(o, dflt): return "'" + json.dumps(o if o is not None else dflt, ensure_ascii=False).replace("'", "''") + "'::jsonb"

def main():
    root = os.getcwd()
    mons = json.load(open(os.path.join(root, 'monster_master.json')))['monsters']
    rows = []
    for order, m in enumerate(mons):
        v = [iv(m.get('monster_id')), s(m.get('code')), s(m.get('name')), s(m.get('rank')),
             iv(m.get('level')), s(m.get('race_code')), s(m.get('spawn_monster_id')),
             nv(m.get('critical_rate')), nv(m.get('critical_damage')),
             iv(m.get('exp_reward')), iv(m.get('currency_reward')), iv(m.get('crd_reward')),
             iv(m.get('guild_point')), iv(m.get('reputation_point')), iv(m.get('hunting_point'))]
        for c in JSONB:
            v.append(jb(m.get(c), {} if c in ('base_stats','scaling','ai_pattern','skill_set') else []))
        v.append(str(order))
        rows.append(v)
    collist = ', '.join(COLS)
    upd = ', '.join(f'{c}=excluded.{c}' for c in COLS if c != 'monster_id')
    def write(path, rws, note):
        with open(path, 'w') as f:
            f.write(f'-- AUTO-GENERATED by import_monsters.py — {note}\nbegin;\n')
            for r in rws:
                f.write(f'insert into public.monsters ({collist})\nvalues ({", ".join(r)})\n'
                        f'on conflict (monster_id) do update set {upd};\n')
            f.write('commit;\n')
    seed = os.path.join(root, 'supabase', 'seed')
    write(os.path.join(seed, 'monsters_seed.sql'), rows, f'{len(rows)} monsters.')
    CHUNK = 80
    for old in [p for p in os.listdir(seed) if p.startswith('monsters_seed_part')]:
        os.remove(os.path.join(seed, old))
    parts = [rows[x:x+CHUNK] for x in range(0, len(rows), CHUNK)]
    for k, ch in enumerate(parts, 1):
        write(os.path.join(seed, f'monsters_seed_part{k:02d}.sql'), ch, f'monsters part {k}/{len(parts)}.')
    print(f'WROTE monsters_seed.sql ({len(rows)}) + {len(parts)} chunks.')

if __name__ == '__main__':
    main()
